<p align="center">
  <img width="600" height="300" src="https://github.com/Moises13r/Rahxion_figures/blob/main/python-numpy.png?raw=true">
</p>



¡Hola!

Este notebook está diseñado como una introducción práctica a **NumPy (Numerical Python)**, una de las bibliotecas fundamentales de Python para el cálculo numérico y el análisis de datos científicos.

NumPy permite trabajar con grandes conjuntos de datos mediante una estructura denominada **`ndarray`**, utilizada para crear y manipular arreglos de una o varias dimensiones. A diferencia de las listas convencionales de Python, estos arreglos están optimizados para realizar operaciones numéricas de manera rápida y con un uso eficiente de la memoria.

A lo largo de este notebook se explorarán algunas de las principales funciones:

* Operaciones matemáticas y algebraicas sobre arreglos.
* Manipulación y transformación de datos.
* Generación de números aleatorios.
* Funciones estadísticas y científicas.
* Base para otras bibliotecas de ciencia de datos como Pandas, SciPy y Matplotlib.

Además, NumPy constituye la base de numerosas herramientas utilizadas en ciencia de datos, ingeniería y computación científica, y se integra con bibliotecas como **Pandas, SciPy y Matplotlib**.

El objetivo es desarrollar una comprensión práctica de NumPy mediante ejemplos y ejercicios que permitan aplicar sus herramientas a la resolución de problemas numéricos y de ingeniería.


*AUTORES*

1. *Ximena Lagunes Quijada*

2. *Moises Velasco Lozano*

# Numpy

<table width="100%">
<tr>
<td bgcolor="#E3F2FD">

# <font color="blue">**1. Introducción** </font>

</td>
</tr>
</table>


NumPy (Numerical Python) es una biblioteca de Python especializada en el cálculo numérico y el análisis de datos, especialmente útil cuando se trabaja con grandes volúmenes de información. Su principal característica es la incorporación de estructuras denominadas arrays, implementadas mediante el objeto **`ndarray`**, que permiten almacenar y organizar datos del mismo tipo en una o varias dimensiones. 

Los arrays pueden representar desde vectores unidimensionales hasta matrices y estructuras multidimensionales, y ofrecen una alternativa más eficiente que las listas convencionales de Python para realizar cálculos numéricos. NumPy está diseñado para procesar estas estructuras de manera rápida, lo que facilita el trabajo con vectores y matrices de grandes dimensiones.

Además de almacenar datos, NumPy proporciona numerosas herramientas para su creación, manipulación, filtrado y procesamiento, así como para realizar operaciones matemáticas directamente sobre los elementos de los arrays. También incorpora funciones de álgebra lineal, como productos de vectores y matrices, cálculo de determinantes, matrices inversas, autovalores, autovectores y resolución de sistemas de ecuaciones.

En este notebook se abordarán los conceptos fundamentales de NumPy mediante ejemplos prácticos, comenzando con la creación y manipulación de arrays, para posteriormente explorar sus principales operaciones y aplicaciones en la resolución de problemas numéricos.

https://numpy.org/

<table width="100%">
<tr>
<td bgcolor="#E3F2FD">

# <font color="blue">**2. Arreglos en Numpy**</font>

</td>
</tr>
</table>

## **2.1 Arreglos**
Antes de comenzar a utilizar NumPy, es importante comprender qué es un arreglo (array), ya que constituye la estructura fundamental con la que trabaja esta biblioteca.

Un arreglo es una colección ordenada de elementos almacenados bajo un mismo nombre. Todos los elementos ocupan una posición específica dentro del arreglo, la cual puede identificarse mediante un índice.

Los arreglos permiten:

* Almacenar grandes cantidades de datos de manera organizada.
* Acceder rápidamente a cualquier elemento mediante su posición.
* Realizar operaciones matemáticas sobre todos los elementos de forma simultánea.

En Python, los arreglos numéricos suelen implementarse mediante la biblioteca NumPy, que está optimizada para cálculos científicos y de ingeniería.

Antes de utilizar NumPy, es necesario importar la biblioteca en nuestro programa. Python no tiene disponibles directamente las funciones especializadas de NumPy para trabajar con arreglos, matrices y operaciones numéricas.

Se importar NumPy de esta manera:

In [1]:
import numpy as np

**NOTA:** La palabra **`as`** permite asignarle un alias a la biblioteca. En este caso, se utiliza **`np`** porque es la forma más común de abreviar NumPy y permite escribir un código más corto y fácil de entender.

**EJEMPLO**:

Supongamos que tenemos las calificaciones de cinco estudiantes. Sin utilizar un arreglo, tendríamos que almacenar cada calificación en una variable diferente:

In [35]:
calificacion_1 = 8.5
calificacion_2 = 9.0
calificacion_3 = 7.5
calificacion_4 = 10.0
calificacion_5 = 8.0

Con NumPy, podemos almacenar todas las calificaciones dentro de un solo arreglo:

In [2]:
calificaciones = np.array([8.5, 9.0, 7.5, 10.0, 8.0])

print(calificaciones)

[ 8.5  9.   7.5 10.   8. ]


De esta manera, todas las calificaciones se encuentran organizadas en una sola estructura y podemos realizar operaciones sobre ellas fácilmente. Por ejemplo, podemos calcular el **promedio del grupo**:

In [3]:
promedio = np.mean(calificaciones)

print("Promedio del grupo:", promedio)

Promedio del grupo: 8.6


## **2.2 Vectores**

Un vector es un arreglo de una sola dimensión (1D) formado por una secuencia ordenada de elementos. En NumPy, los vectores permiten almacenar varios valores dentro de una misma estructura y acceder a cada uno de ellos mediante su posición o índice.

Los vectores se utilizan para representar:

* Coordenadas en el espacio.
* Mediciones experimentales.
* Series de datos.
* Características de un objeto en aprendizaje automático.

**EJEMPLO:**

Supongamos que queremos almacenar las temperaturas registradas durante siete días. En lugar de crear una variable para cada día, podemos representar todas las mediciones mediante un vector:

In [4]:
temperaturas = np.array([22, 24, 23, 25, 27, 26, 24])

print(temperaturas)

[22 24 23 25 27 26 24]


En este caso,**`temperaturas`** es un vector de siete elementos, donde cada posición corresponde a la temperatura registrada en un día de la semana.

## **2.3 Matrices**

Una matriz es un arreglo de dos dimensiones (2D) en el que los elementos se encuentran organizados en filas y columnas. En NumPy, las matrices permiten almacenar y trabajar con conjuntos de datos relacionados dentro de una misma estructura.

Las matrices se utilizan para representar diferentes tipos de información, por ejemplo:

* Tablas de datos numéricos.
* Mediciones de diferentes variables.
* Datos experimentales.
* Sistemas de ecuaciones.
* Información de diferentes muestras u observaciones.

**EJEMPLO:**

Supongamos que queremos almacenar las calificaciones de cuatro estudiantes en tres materias diferentes. Podemos organizar esta información mediante una matriz, donde cada fila representa a un estudiante y cada columna representa una materia:

In [5]:
calificaciones = np.array([
    [8, 9, 10],
    [7, 8, 9],
    [9, 10, 9],
    [8, 7, 10]
])

print(calificaciones)

[[ 8  9 10]
 [ 7  8  9]
 [ 9 10  9]
 [ 8  7 10]]


En este caso, **`calificaciones`** es una matriz de 4 filas y 3 columnas. Es decir, contiene las calificaciones de 4 estudiantes en 3 materias.

<table width="100%">
<tr>
<td bgcolor="#E3F2FD">

# <font color="blue">**3. Creación de arreglos**</font>

</td>
</tr>
</table>

En NumPy, un arreglo puede crearse de diferentes maneras dependiendo de los datos que tengamos disponibles y del tipo de arreglo que necesitemos. No siempre será necesario escribir manualmente todos los valores que formarán parte del arreglo, ya que NumPy proporciona funciones que permiten **generarlos automáticamente**.

Por ejemplo, podemos crear un arreglo a partir de una lista de datos que ya conocemos, como las temperaturas registradas durante una semana. También podemos crear arreglos de un tamaño determinado y llenarlos automáticamente con ceros, unos o cualquier otro valor.

Además, NumPy permite generar secuencias de números indicando un intervalo o la cantidad de valores que queremos obtener. De la misma manera, podemos crear arreglos con números aleatorios, lo cual resulta especialmente útil para realizar simulaciones, generar datos de prueba o trabajar con métodos numéricos.

Por esta razón, NumPy cuenta con distintas funciones para la creación de arreglos, entre las que se encuentran np.array(), np.zeros(), np.ones(), np.eye(), np.full(), np.arange(), np.random.rand(), np.random.randint() y np.linspace().  

* **np.array()**
  
La función **`np.array()`** se utiliza para crear arreglos en NumPy. Un arreglo es una estructura que permite almacenar y organizar varios valores dentro de una misma variable, facilitando el manejo y las operaciones con los datos.

La dimensión del arreglo dependerá de cómo estén organizados los datos que introduzcamos.

Si utilizamos una lista simple, NumPy crea un arreglo de una dimensión (1D), es decir, un vector.

*Sintaxis básica:*

np.array(datos)

**EJEMPLO:** Podemos almacenar las temperaturas registradas durante cinco días

In [41]:
temperaturas = np.array([22, 24, 23, 26, 25])

print(temperaturas)

[22 24 23 26 25]


En cambio, si organizamos los datos en filas y columnas, NumPy puede crear un arreglo de dos dimensiones (2D), es decir, una matriz.

**Ejemplo:** Podemos representar las calificaciones de tres estudiantes en tres materias

In [6]:
calificaciones = np.array([
    [8, 9, 10],
    [7, 8, 9],
    [9, 10, 8]
])

print(calificaciones)

[[ 8  9 10]
 [ 7  8  9]
 [ 9 10  8]]


* **np.zeros()**

La función **`np.zeros()`** crea un arreglo en el que todos los elementos tienen un valor inicial de cero. Las dimensiones del arreglo se especifican dentro de la función.

*Sintaxis básica:*

np.zeros(dimensiones)

**Ejemplo**: Para crear una matriz de 3 filas y 4 columnas llena de ceros:

In [7]:
ceros = np.zeros((3, 4))

print(ceros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**NOTA:**
Esta función es útil cuando necesitamos inicializar una matriz para posteriormente almacenar o calcular nuevos valores.

* **np.ones()**
  
La función **`np.ones()`** funciona de manera similar a **`np.zeros()`**, pero crea un arreglo en el que todos los elementos tienen el valor 1.

*Sintaxis básica:*

np.ones(dimensiones)

**Ejemplo:** Para crear una matriz de 2 filas y 4 columnas llenas del valor de 1. 

In [8]:
unos = np.ones((2, 4))

print(unos)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


* **np.full()**

La función **`np.full()`** permite crear un arreglo con determinadas dimensiones y llenar todos sus elementos con un valor específico.

*Sintaxis básica:*

np.full(dimensiones, valor)

**Ejemplo:** Supongamos que queremos crear una matriz de 2 filas y 3 columnas donde todos los valores iniciales sean 10:

In [48]:
matriz = np.full((2, 3), 10)

print(matriz)

[[10 10 10]
 [10 10 10]]


* **np.eye()**

La función **`np.eye()`** permite crear una matriz cuyos elementos son ceros, excepto aquellos que se encuentran en una diagonal determinada, los cuales tienen el valor 1.

*Sintaxis básica:*

np.eye(n)

Donde **`n`** representa el número de filas y columnas de la matriz cuadrada.

**Ejemplo:** Podemos crear una matriz identidad de 3 × 3:

In [9]:
identidad = np.eye(3)

print(identidad)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Una característica importante de **`np.eye()`** es que no está limitada a matrices cuadradas. Podemos indicar por separado el número de filas y columnas.

**Ejemplo:** Para crear una matriz de 3 filas y 5 columnas:

In [10]:
matriz = np.eye(3, 5)

print(matriz)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


* **np.arange()**

La función **`np.arange()`** permite crear un arreglo con una secuencia de valores separados por un determinado intervalo o paso. 

*Sintaxis básica:*

np.arange(inicio, fin, paso)

**Ejemplo:** Queremos generar números desde 0 hasta 20 avanzando de 2 en 2:

In [53]:
numeros = np.arange(0, 20, 2)

print(numeros)

[ 0  2  4  6  8 10 12 14 16 18]


* **np.linspace()**

La función **`np.linspace()`** crea un arreglo con una cantidad determinada de valores igualmente espaciados entre un valor inicial y uno final.

*Sintaxis básica:*

np.linspace(inicio, fin, cantidad)

Donde **`cantidad`** es el número de valores que queremos generar.

**Ejemplo:** Queremos generar cinco valores igualmente espaciados entre 0 y 10:

In [12]:
valores = np.linspace(0, 10, 5)

print(valores)

[ 0.   2.5  5.   7.5 10. ]


**NOTA:**
Una diferencia importante con **`np.arange()`** es que aquí indicamos cuántos valores queremos obtener, en lugar de indicar directamente el tamaño del paso. Además, de manera predeterminada, **`linspace()`** sí incluye el valor final.

* **np.random.rand()**

La función **`np.random.rand()`** permite generar arreglos de números pseudoaleatorios de punto flotante distribuidos uniformemente entre 0 y 1 (incluye 0 pero no 1).

*Sintaxis básica:*

np.random.rand(filas, columnas)

**Ejemplo:** Para generar una matriz de 2 filas y 3 columnas:

In [13]:
aleatorios = np.random.rand(2, 3)

print(aleatorios)

[[0.28661413 0.98562224 0.85323743]
 [0.00365704 0.19991585 0.14034301]]


* **np.random.randint()**

La función **`np.random.randint()`** genera números enteros pseudoaleatorios dentro de un intervalo determinado.

*Sintaxis básica:*

np.random.randint(inicio, fin, size)

**Ejemplo:** Supongamos que queremos generar cinco calificaciones enteras aleatorias entre 5 y 10:

In [14]:
calificaciones = np.random.randint(5, 11, size=5)

print(calificaciones)

[5 8 5 6 6]


<table width="100%">
<tr>
<td bgcolor="#E3F2FD">

# <font color="blue">**4. Dimensiones**</font>

</td>
</tr>
</table>

En NumPy, las dimensiones indican la forma en que los datos están organizados dentro de un arreglo. Dependiendo de cómo se agrupen los elementos, un arreglo puede tener una, dos, tres o más dimensiones.

Cada dimensión puede entenderse como un nivel de organización de los datos. Por ejemplo, un solo valor corresponde a un arreglo de cero dimensiones (0D), una secuencia de valores forma un arreglo de una dimensión (1D) y una estructura organizada en filas y columnas corresponde a un arreglo de dos dimensiones (2D).

Podemos visualizarlo de la siguiente manera:

- 0D → Escalar: contiene un único valor, como el número `5`.
- 1D → Vector: contiene una secuencia de valores.
- 2D → Matriz: contiene valores organizados en filas y columnas.
- 3D → Arreglo tridimensional: puede visualizarse como un conjunto de matrices.

Conocer las dimensiones y características de un arreglo es importante para saber cómo están organizados los datos y cómo podemos trabajar con ellos. Para obtener esta información, NumPy proporciona atributos como `.ndim`, `.shape`, `.size` y `.dtype`.

* **.ndim**

El atributo  `.ndim ` permite conocer el número de dimensiones o ejes que tiene un arreglo.

*Sintaxis básica:*

arreglo.ndim

**EJEMPLO:**

In [15]:
matriz = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print("MATRIZ")
print(matriz.ndim)

vector = np.array([10, 20, 30, 40])
print("VECTOR")
print(vector.ndim)


MATRIZ
2
VECTOR
1


**NOTA:**

El resultado es `2` porque `matriz` está organizado mediante filas y columnas, por lo que se trata de un arreglo bidimensional.

El resultado es `1` porque `vector` tiene una sola dimensión.


* **.shape**

El atributo `.shape` permite conocer cómo están distribuidos los elementos en cada dimensión del arreglo.

*Sintaxis básica:*

arreglo.shape

**EJEMPLO:**

In [16]:
matriz = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(matriz.shape)

(2, 3)


**NOTA:**
El resultado (2, 3) significa que el arreglo tiene 2 filas y 3 columnas

* **.size** 
    
El atributo `.size` indica la cantidad total de elementos almacenados dentro de un arreglo, independientemente de cómo estén distribuidos.

*Sintaxis básica:*

arreglo.size

**EJEMPLO:**

In [18]:
matriz = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(matriz.size)

6


**NOTA:**

La respuesta muestra que tiene 6 elementos en la matriz.

El atributo `.size` es util cuando se quiere saber cuántos datos contiene un arreglo.


* **.dtype** 

El atributo .dtype permite conocer el tipo de dato que NumPy utiliza para almacenar los elementos de un arreglo.

*Sintaxis básica:*

arreglo.dtype

**EJEMPLO:**

In [19]:
import numpy as np
numeros = np.array([10, 20, 30, 40])

print(numeros.dtype)

int64


**NOTA:**

El resultado `int64` indica que los elementos están almacenados como números enteros.

In [20]:
temperaturas = np.array([22.5, 23.8, 25.1, 24.6])

print(temperaturas.dtype)

float64


**NOTA:**

El resultado `float64` indica que los elementos están almacenados son números decimales.

<table width="100%">
<tr>
<td bgcolor="#E3F2FD">

# <font color="blue">**5. Cambiar dimensiones**</font>

</td>
</tr>
</table>

En NumPy, los datos de un arreglo pueden reorganizarse o cambiar su número de dimensiones sin necesidad de introducir nuevamente sus valores. Esto es útil cuando necesitamos adaptar la estructura de los datos para realizar cálculos, trabajar con matrices o preparar información para otros procesos.

NumPy proporciona diferentes herramientas para modificar la estructura de los arreglos, entre ellas `reshape()`, `flatten()`, `ravel()`, `transpose()`, `expand_dims()` y `squeeze()`.

* **reshape()**
  
El método `reshape()` permite cambiar la forma de un arreglo, es decir, reorganizar sus elementos en un número diferente de filas, columnas o dimensiones.

*Sintaxis básica:*

arreglo.reshape(filas, columnas)

**EJEMPLO: Al inicio se tiene un vector de 6 elementos**

In [22]:
numeros = np.array([1, 2, 3, 4, 5, 6])

print(numeros)
print(numeros.shape)

[1 2 3 4 5 6]
(6,)


**Podemos convertirlo en una matriz de 2 filas y 3 columnas:**

In [23]:
matriz = numeros.reshape(2, 3)

print(matriz)

print(matriz.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


**NOTA:** La nueva forma también debe contener 6 elementos. Por ejemplo, 2 × 3 = 6 o 3 × 2 = 6.

* **flatten()**

El método `flatten()` permite convertir un arreglo de varias dimensiones en un arreglo de una sola dimensión (1D). Utilizado para convertir una matriz en un vector.

*Sintaxis básica:*

arreglo.flatten()

**EJEMPLO: La matriz de dimensiones (2, 3) se va a convertir en un vector de 6 elementos.**

In [73]:
matriz = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(matriz)

[[1 2 3]
 [4 5 6]]


**`flatten()` va a crear una copia independiente de los datos. Por lo tanto, modificar el nuevo vector no modifica el arreglo original.**

In [74]:
vector = matriz.flatten()

print(vector)

[1 2 3 4 5 6]


* **ravel()**
  
El método `ravel()` también permite convertir un arreglo multidimensional en un arreglo de una sola dimensión.

La diferencia principal entre `flatten()` y `ravel()` está en cómo manejan los datos en la memoria
.
En  `flatten()` la matriz original no cambia porque creo una copia independiente.

En `ravel()`evita crear una copia de los datos. Esto significa que el nuevo arreglo y el original pueden compartir la misma información en memoria.

*Sintaxis básica:*

arreglo.ravel()

**EJEMPLO:**

In [24]:
matriz = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

vector = matriz.ravel()

print(vector)


[10 20 30 40 50 60]


**Al modificar un valor en la posición 0 del vector, también se modifica en la matriz porque comparten los mismos datos en memoria.**

In [25]:
vector[0] = 100

print(vector)
print(matriz)

[100  20  30  40  50  60]
[[100  20  30]
 [ 40  50  60]]


* **transpose()**

El método `transpose()` permite cambiar la posición de los datos de una matriz, haciendo que las filas pasen a ser columnas y las columnas pasen a ser filas.

*Sintaxis básica:*

* arreglo.transpose()

* arreglo.T

**EJEMPLO: Tenemos una matriz de 2 filas y 3 columnas:**

In [80]:
matriz = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(matriz)

[[1 2 3]
 [4 5 6]]


**Al aplicar la transposición la matriz va a pasar de
2 filas × 3 columnas a 3 filas × 2 columnas**

In [81]:
transpuesta = matriz.transpose()

print(transpuesta)

[[1 4]
 [2 5]
 [3 6]]


* **np.expand_dims()**

La función `np.expand_dims()` permite agregar una nueva dimensión a un arreglo.

A diferencia de `reshape()`, aquí indicamos principalmente en qué posición queremos agregar el nuevo eje mediante el parámetro `axis`.

*Sintaxis básica:*

np.expand_dims(arreglo, axis)

**EJEMPLO:**

In [26]:
vector = np.array([10, 20, 30])
print(vector)

print(vector.shape)

[10 20 30]
(3,)


**Se agrega una nueva dimensión**

In [27]:
nuevoD = np.expand_dims(vector, axis=1)

print(nuevoD)
print(nuevoD.shape)

[[10]
 [20]
 [30]]
(3, 1)


* **np.squeeze()**

La función `.squeeze()` permite eliminar las dimensiones innecesarias de un arreglo, específicamente aquellas que contienen un solo elemento pero no elimina datos. Los valores del arreglo permanecen iguales; lo único que cambia es la forma `.shape` en la que están organizados.

*Sintaxis básica:*

np.squeeze(arreglo)

**EJEMPLO 1: Se un arreglo con 3 columnas y 1 fila**

In [86]:
datos = np.array([[10, 20, 30]])

print(datos)
print(datos.shape)

[[10 20 30]]
(1, 3)


**Eliminamos la dimensión de tamaño 1**

In [87]:
nuevo = datos.squeeze()

print(nuevo)
print(nuevo.shape)

[10 20 30]
(3,)


**EJEMPLO 2: Se un arreglo con 3 filas y 1 columna:**

In [88]:
import numpy as np

datos = np.array([
    [10],
    [20],
    [30]
])

print(datos)
print(datos.shape)

[[10]
 [20]
 [30]]
(3, 1)


**Eliminamos la dimensión de tamaño 1**

In [89]:
nuevo = np.squeeze(datos)

print(nuevo)
print(nuevo.shape)

[10 20 30]
(3,)


**NOTA: `np.squeeze()` elimina dimensiones de tamaño 1, pero nunca elimina los datos que contiene el arreglo.**

<table width="100%">
<tr>
<td bgcolor="#E3F2FD">

# <font color="blue">**6. Operaciones matemáticas**</font>

</td>
</tr>
</table>

Una de las principales ventajas de NumPy es que permite realizar operaciones matemáticas directamente sobre los elementos de un arreglo, sin necesidad de recorrerlos individualmente mediante ciclos.

## **6.1 Operaciones aritméticas**

**Suma:**           + o `np.add()`

**Resta:**          - o `np.subtract()`

**Multiplicación:** * o `np.multiply()`

**División**        / o `np.divide()`

**Potencia:**       ** o `np.power()`

**EJEMPLOS:**

In [28]:
a = np.array([10, 20, 30])
b = np.array([2, 4, 5])

print("Suma:")
print(a + b)
print("Resta:")
print(a - b)
print("Multiplicación:")
print(a * b)
print("División:")
print(a / b)

Suma:
[12 24 35]
Resta:
[ 8 16 25]
Multiplicación:
[ 20  80 150]
División:
[5. 5. 6.]


## **6.2 Funciones matemáticas**

**Raíz cuadrada:** `np.sqrt()`

**Exponencial:** `np.exp()`

**Logaritmo natural:** `np.log()`

**Valor absoluto:** `np.abs() `

**EJEMPLOS:**

In [29]:
numeros = np.array([1, 4, 9, 16])

print("Raíz cuadrada:", np.sqrt(numeros))

print("Exponencial:", np.exp(numeros))

print("Logaritmo:", np.log(numeros))

print("Valor absoluto:", np.abs(numeros))

Raíz cuadrada: [1. 2. 3. 4.]
Exponencial: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
Logaritmo: [0.         1.38629436 2.19722458 2.77258872]
Valor absoluto: [ 1  4  9 16]


**Seno:** `np.sin()`  
**Coseno:** `np.cos()`

**EJEMPLOS:**

In [30]:
angulos = np.array([0, 30, 45, 90])
radianes = np.deg2rad(angulos)

print("Seno:", np.sin(radianes))

print("Coseno:", np.cos(radianes))

Seno: [0.         0.5        0.70710678 1.        ]
Coseno: [1.00000000e+00 8.66025404e-01 7.07106781e-01 6.12323400e-17]


## **6.3 Operaciones por ejes**

Cuando trabajamos con una matriz, podemos realizar una operación sobre todos los datos, o podemos pedirle a NumPy que la realice separadamente según sus filas o columnas. Para ello se utiliza el parámetro `axis`.

En una matriz de dos dimensiones:

* `axis=0` → obtiene un resultado para cada columna.
* `axis=1` → obtiene un resultado para cada fila.

**EJEMPLO:Se tienen las calificaciones de 3 estudiantes en 3 materias.**

**Si queremos conocer el promedio de cada materia, necesitamos trabajar por columnas:**


In [31]:
calificaciones = np.array([
    [8,  9, 10],
    [7,  8,  9],
    [9, 10,  8]
])

print("Operación por columnas: axis=0")
np.mean(calificaciones, axis=0)

Operación por columnas: axis=0


array([8., 9., 9.])

**EJEMPLO:**

**Si queremos conocer el promedio de cada estudiante. Como cada estudiante corresponde a una fila:**

In [32]:
print("Operación por filas: axis=1")
np.mean(calificaciones, axis=1)

Operación por filas: axis=1


array([9., 8., 9.])

**Nota:** Puede utilizarse en funciones como `np.sum()`, `np.mean()`, `np.max()`, `np.min()` y `np.std()`, entre otras.

<table width="100%">
<tr>
<td bgcolor="#E3F2FD">

# <font color="blue">**7. Operaciones vectorizadas**</font>

</td>
</tr>
</table>

Las operaciones vectorizadas permiten realizar cálculos directamente sobre todos los elementos de un arreglo de NumPy, sin necesidad de recorrer cada elemento mediante un ciclo `for`.


## **7.1 Operaciones con escalares**

NumPy permite realizar una operación entre un arreglo y un escalar.

**EJEMPLO:**

In [33]:
numeros = np.array([1, 2, 3, 4])

resultado = numeros * 2

print(resultado)

[2 4 6 8]


**NOTA:** También funciona con otras operaciones.

## **7.2 Operaciones elemento por elemento**

NumPy también permite realizar operaciones entre dos arreglos. Cuando tienen formas compatibles, la operación puede realizarse entre los elementos correspondientes.

**EJEMPLO:**

In [34]:
a = np.array([10, 20, 30])
b = np.array([2, 4, 5])

resultado = a * b

print(resultado)

[ 20  80 150]


## **7.3 Comparaciones vectorizadas**

NumPy permite comparar todos los elementos de un arreglo con un valor mediante operadores como `>`, `<`, `>=`, `<=`, `==` y `!=`.

El resultado es un arreglo de valores booleanos:

* True → se cumple la condición.
* False → no se cumple la condición.

**EJEMPLO:**

In [35]:
edades = np.array([18, 15, 23, 16, 30])

resultado = edades >= 18

print(resultado)

[ True False  True False  True]


<table width="100%">
<tr>
<td bgcolor="#E3F2FD">

# <font color="blue">**8. Estadística**</font>

</td>
</tr>
</table>

NumPy proporciona diferentes funciones que permiten realizar cálculos estadísticos sobre los datos almacenados en un arreglo. Estas herramientas son útiles para resumir y analizar conjuntos de datos, permitiendo identificar valores representativos, conocer su dispersión y determinar cómo se distribuyen.

Entre las principales operaciones estadísticas se encuentran la `media`, `mediana`, `desviación estándar`, `varianza`, `valores mínimo` y `máximo`y `percentiles`.


## **8.1 Media**

La media aritmética `np.mean()`, también conocida como promedio, representa un valor central de un conjunto de datos. Se obtiene sumando todos los valores y dividiendo el resultado entre el número total de elementos.

**EJEMPLO:**

In [36]:
datos = np.array([10, 12, 14, 16, 18])

media = np.mean(datos)

print("Media:", media)


Media: 14.0


## **8.2 Mediana**

La mediana `np.median()` es el valor que se encuentra en el centro de un conjunto de datos después de ordenarlos de menor a mayor. Si existe un número impar de elementos, corresponde al valor central. Si existe un número par, se obtiene el promedio de los dos valores centrales.

**EJEMPLO:**

In [37]:
mediana = np.median(datos)

print("Mediana:", mediana)

Mediana: 14.0


## **8.3 Desviación estándar**

La desviación estándar `np.std()` indica qué tan dispersos o alejados se encuentran los datos respecto a la media. Una desviación estándar pequeña indica que los valores se encuentran relativamente cerca de la media, mientras que una desviación estándar grande indica una mayor dispersión.

**EJEMPLO:**

In [38]:
desviacion = np.std(datos)

print("Desviación estándar:", desviacion)

Desviación estándar: 2.8284271247461903


## **8.4 Varianza**

La varianza `np.var()` también mide la dispersión de los datos respecto a la media. Se obtiene a partir de las diferencias entre cada valor y la media elevadas al cuadrado.

**EJEMPLO:**

In [39]:
varianza = np.var(datos)

print("Varianza:", varianza)

Varianza: 8.0


## **8.5 Valor mínimo**

La función `np.min()` permite encontrar el valor más pequeño contenido en un arreglo.

**EJEMPLO:**

In [40]:
minimo = np.min(datos)

print("Valor mínimo:", minimo)

Valor mínimo: 10


## **8.6 Valor máximo**

La función `np.max()` permite encontrar el valor más grande contenido en un arreglo.

**EJEMPLO:**

In [41]:
maximo = np.max(datos)

print("Valor máximo:", maximo)

Valor máximo: 18


## **8.7 Percentiles**

Los percentiles `np.percentile()` son valores que permiten dividir un conjunto de datos ordenados en 100 partes. Se utilizan para conocer cómo se distribuyen los datos y determinar qué porcentaje de las observaciones se encuentra en o por debajo de cierto valor.

**EJEMPLO:**

In [42]:
datos = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

print(np.percentile(datos, 25))
print(np.percentile(datos, 50))
print(np.percentile(datos, 75))


30.0
50.0
70.0


Los resultados significan:

P25 = `30` → aproximadamente el 25 % de los datos está en o por debajo de `30`.

P50 = `50` → aproximadamente el 50 % de los datos está en o por debajo de `50`.

P75 = `70` → aproximadamente el 75 % de los datos está en o por debajo de `70`.

<table width="100%">
<tr>
<td bgcolor="#E3F2FD">

# <font color="blue">**9. Álgebra lineal**</font>

</td>
</tr>
</table>

El álgebra lineal es una rama de las matemáticas que trabaja principalmente con vectores, matrices y sistemas de ecuaciones. NumPy proporciona herramientas que permiten realizar estas operaciones de forma directa mediante funciones como `Producto punto`, `Multiplicación matricial`, `Determinante`, `Matriz inversa` y `Resolver sistemas de ecuaciones`.


## **9.1 Producto punto**

El producto punto o producto escalar `np.dot()` es una operación entre dos vectores del mismo tamaño. Consiste en multiplicar los elementos que ocupan la misma posición y después sumar los resultados.

**EJEMPLO:**

In [43]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

resultado = np.dot(a, b)

print("Producto punto:", resultado)

Producto punto: 32


## **9.2 Multiplicación matricial**

La multiplicación matricial `np.matmul()` permite multiplicar dos matrices siguiendo una regla diferente a la multiplicación elemento por elemento. Para obtener cada elemento de la matriz resultante, se toma una fila de la primera matriz y una columna de la segunda, se multiplican sus elementos correspondientes y finalmente se suman.

**EJEMPLO:**

In [44]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

resultado = np.matmul(A, B)
print(resultado)

[[19 22]
 [43 50]]


## **9.3 Determinante**

El determinante `np.linalg.det()` es un único valor numérico que se obtiene a partir de una matriz cuadrada, es decir, una matriz que tiene el mismo número de filas y columnas.

**EJEMPLO:**

In [45]:
A = np.array([
    [1, 2],
    [3, 4]
])

determinante = np.linalg.det(A)

print("Determinante:", determinante)

Determinante: -2.0000000000000004


## **9.4 Matriz inversa**

La matriz inversa `np.linalg.inv()` es una matriz asociada a otra matriz cuadrada.

La matriz identidad funciona de manera parecida al número 1 en una multiplicación común.

**EJEMPLO:**

In [46]:
A = np.array([
    [1, 2],
    [3, 4]
])

inversa = np.linalg.inv(A)

print(inversa)

[[-2.   1. ]
 [ 1.5 -0.5]]


**Su característica principal es que, cuando una matriz A se multiplica por su matriz inversa, el resultado es la matriz identidad.**

In [47]:
Identidad= np.matmul(A, inversa)

print(np.round(Identidad))

[[1. 0.]
 [0. 1.]]


**NOTA:** `np.round()` es para redondear el resultado.

## **9.5 Resolver sistemas de ecuaciones**

En NumPy también permite resolver sistemas de ecuaciones lineales con `np.linalg.solve()`.

**EJEMPLO:**

**Se tiene el siguiente sistema de ecuaciones:**
$$
2x+y=5
$$
$$
x−y=1
$$
**Este sistema puede representarse en forma matricial mediante:**
$$
Ax=b
$$
**En la matriz A contiene los coeficientes de las incógnitas y el vector B contiene los resultados de las ecuaciones.**

In [48]:
A = np.array([
    [2,  1],
    [1, -1]
])

b = np.array([5, 1])

solucion = np.linalg.solve(A, b)

print(solucion)

[2. 1.]


$
x = 2
$

$
y = 1
$